const CLASS_NAMES = {
  base: 'textae-editor__type-pallet',
  baseEntity: 'textae-editor__type-pallet--entity',
  baseRelation: 'textae-editor__type-pallet--relation',
  title: 'textae-editor__type-pallet__title',
  titleText: 'textae-editor__type-pallet__title-text',
  lockIcon: 'textae-editor__type-pallet__lock-icon',
  buttons: 'textae-editor__type-pallet__buttons',
  button: 'textae-editor__type-pallet__button',
  buttonAdd: 'textae-editor__type-pallet__add-button',
  buttonRead: 'textae-editor__type-pallet__read-button',
  buttonWrite: 'textae-editor__type-pallet__write-button',
  buttonWriteTransit: 'textae-editor__type-pallet__write-button--transit',
  hideWhenLocked: 'textae-editor__type-pallet__hide-when-locked',
  hideWhenLockedHide: 'textae-editor__type-pallet__hide-when-locked--hide',
  row: 'textae-editor__type-pallet__row',
  label: 'textae-editor__type-pallet__label',
  link: 'textae-editor__type-pallet__link',
  defaultIcon: 'textae-editor__type-pallet__default-icon',
  shortLabel: 'textae-editor__type-pallet__short-label',
  useNumber: 'textae-editor__type-pallet__use-number',
  tableButtons: 'textae-editor__type-pallet__table-buttons',
  tableButton: 'textae-editor__type-pallet__table-button',
  selectAll: 'textae-editor__type-pallet__select-all',
  editType: 'textae-editor__type-pallet__edit-type',
  remove: 'textae-editor__type-pallet__remove',
  tableButtonDisabled: 'textae-editor__type-pallet__table-button--disabled',
  noConfig: 'textae-editor__type-pallet__no-config'
}

export default CLASS_NAMES
