export default function(commander, presenter, persistenceInterface) {
  return new Map([
    ['1', (options) => presenter.event.manipulateAttribute(options, 1)],
    ['2', (options) => presenter.event.manipulateAttribute(options, 2)],
    ['3', (options) => presenter.event.manipulateAttribute(options, 3)],
    ['4', (options) => presenter.event.manipulateAttribute(options, 4)],
    ['5', (options) => presenter.event.manipulateAttribute(options, 5)],
    ['6', (options) => presenter.event.manipulateAttribute(options, 6)],
    ['7', (options) => presenter.event.manipulateAttribute(options, 7)],
    ['8', (options) => presenter.event.manipulateAttribute(options, 8)],
    ['9', (options) => presenter.event.manipulateAttribute(options, 9)],
    ['a', commander.redo],
    ['b', () => presenter.event.toggleDetectBoundaryMode()],
    ['c', () => presenter.event.copyEntities()],
    ['d', () => presenter.event.removeSelectedElements()],
    ['e', () => presenter.event.createEntity()],
    ['f', () => presenter.event.toggleInstaceRelation()],
    ['i', () => persistenceInterface.importAnnotation()],
    ['m', () => presenter.event.toggleInstaceRelation()],
    ['q', () => presenter.event.showPallet()],
    ['r', () => presenter.event.replicate()],
    ['s', () => presenter.event.speculation()],
    ['u', () => persistenceInterface.uploadAnnotation()],
    ['v', () => presenter.event.pasteEntities()],
    ['w', () => presenter.event.changeLabel()],
    ['x', () => presenter.event.negation()],
    ['y', commander.redo],
    ['z', commander.undo],
    ['ArrowDown', () => presenter.event.selectDown()],
    ['ArrowLeft', (option) => presenter.event.selectLeft(option)],
    ['ArrowRight', (option) => presenter.event.selectRight(option)],
    ['ArrowUp', () => presenter.event.selectUp()],
    ['Backspace', () => presenter.event.removeSelectedElements()],
    ['Delete', () => presenter.event.removeSelectedElements()],
    ['Escape', () => presenter.event.cancelSelect()]
  ])
}
